### ISSUE TITLE
followed the instructions and i get no global moment variable

### ISSUE THREAD

**Issue by mgenev** [keydunov/ember-cli-moment#1]

**Comment by keydunov** [comment]
Which version of ember-cli do you use?

I have created example app with ember-cli (0.0.46) and ember-cli-moment https://github.com/keydunov/ember-cli-moment-example

Please check it out, if it does't help please provide more details about your setup.

Thank you

**Comment by mgenev** [comment]
I guess we're at .43 which was 2  weeks ago's version? .45 came out last night I thought?

**Comment by keydunov** [comment]
It should work with .43 too, was example app helpful?

**Comment by keydunov** [comment]
ember-cli-moment has been deprecated in favor of [ember-moment](https://github.com/stefanpenner/ember-moment).
