### ISSUE TITLE
I accidentally created something similar

### ISSUE THREAD

**Issue by stefanpenner** [keydunov/ember-cli-moment#4]
I was caught in the heat of making an addon, and did not realize this repo already existed.

Anyways, I have created something similar: https://github.com/stefanpenner/ember-moment

With the exceptions:
- uses the the new addon api
- uses blueprint to install moment via bower
- provides `moment` and `ago` template helper
- provides some basic tests

I would prefer we consolidate, if you are interested I'll gladly give you commit to `ember-moment` and we can deprecate this one.

**Comment by keydunov** [comment]
Sure, `ember-moment` looks great and `ember-cli-moment` should be deprecated in favor of `ember-moment`.

**Comment by stefanpenner** [comment]
@keydunov do you want me to do the deprecation, or would you like to?

I think it should be a 2 part explanation.
1. if you need just moment, use `bower install momentjs --save`
2. if you need components and helpers use the addon npm `install ember-moment --save` (which happens to do `bower install momentjs --save` for you.

**Comment by keydunov** [comment]
@stefanpenner I have added deprecation message to readme, as you suggested above, please feel free to change it if you wish.

**Comment by crunchtime-ali** [comment]
It would be cool if you'd add a link to ember-moment in the readme and a note that this project has been superseded by it.

**Comment by keydunov** [comment]
I have updated it on npm, so now it includes deprecation message and link to ember-moment addon in readme.

**Comment by crunchtime-ali** [comment]
Thanks a lot :+1:

**Comment by stefanpenner** [comment]
@keydunov you now also have commit to stefanpenner/ember-moment looking forward to further collaboration.

**Comment by keydunov** [comment]
@stefanpenner thank you.
